### ISSUE TITLE
Custom preset file bitrate is hardcoded - #future #development

### ISSUE THREAD

**Issue by itorian** [itorian/Azure-Media-Services-Upload-and-Play-Videos-in-MVC#3]
If you notice in custom preset file, I removed higher bitrate encoding from my preset file and this does the work. This has one disadvantage, any superb video quality will be loose quality in encoding because preset is hardcoded for every video file. But, at-least now I have opportunity to write this bitrate dynamically based on video being uploaded through our service. And then send this new bitrate to Azure Media Services.

This is future work for this project.

**Comment by edagtc** [comment]
Hello, good afternoon
I'm starting in this world of ASP .net .. and the truth is very useful for your project ... it's the change I have with everything and that ... but my doubt is to use a database to save the videos, if What would only be ... or only added to azure's assets?

**Comment by itorian** [comment]
@edagtc storing video in database is a bad idea. you should think about azure storage, or even azure media services if you want secured delivery and digital rights management. 

Custom preset development: this feature was developed with commit https://github.com/itorian/Azure-Media-Services-Upload-and-Play-Videos-in-MVC/commit/5b51d0aaf0c6a1be3f0e4831840080238bba3bff
